import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthHeader from "@/components/AuthHeader";
import { getUserInfo } from "@/actions/user/user.actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getUserInfo(); // 사용자 정보 가져오기 Server Action 호출

  return (
    <html lang="ko">
      <body className={inter.className}>
        <AuthHeader user={user} />
        {children}
      </body>
    </html>
  );
}
